#!/usr/bin/env python

from __future__ import with_statement

import os
import sys
import getpass

from fogbugz import FogBugz
from ConfigParser import ConfigParser

if os.name == 'nt':
    FBCLI_SETTINGS_PATH = os.path.expanduser(os.path.join('~', 'fbcli.ini'))
else:
    FBCLI_SETTINGS_PATH = os.path.expanduser(os.path.join('~', '.fbcli'))

config = ConfigParser()
config.read(FBCLI_SETTINGS_PATH)

def save_config(f):
    'Make the provided function always save the configuration file'
    def wrapper(*args):
        f(*args)
        with open(FBCLI_SETTINGS_PATH, 'w') as configfile:
            config.write(configfile)
    return wrapper

def fb(login=None, password=None):
    'Return an as-initialized-as-can-be FogBugz object'
    if config.has_section('fogbugz'):
        active = config.get('fogbugz', 'active')
        url = config.get('urls', active)

        if not login:
            token = config.get('tokens', active)
            return FogBugz(url, token=token)
        else:
            f = FogBugz(url)
            f.logon(login, password)
            return f
    else:
        print 'FogBugz URL: ',
        url = sys.stdin.readline().strip()
        print 'Alias: ',
        alias = sys.stdin.readline().strip()
        add([alias, url])
        return fb(login, password)

def active(args):
    alias = config.get('fogbugz', 'active')
    url = config.get('urls', alias)
    print '%s (%s)' % (alias, url)

@save_config
def add(args):
    'Add a new FogBugz install to the list of known installs'
    if not config.has_section('urls'):
        config.add_section('urls')
    if not config.has_section('fogbugz'):
        config.add_section('fogbugz')
    alias = args[0]
    url = args[1]
    config.set('urls', alias, url)
    config.set('fogbugz', 'active', alias)

@save_config
def login(args):
    'Log on with the credentials provided and save the token for later use'
    print "Email: ",
    email = sys.stdin.readline().strip()
    password = getpass.getpass()
    
    f = fb(email, password)
    if not config.has_section('tokens'):
        config.add_section('tokens')
    config.set('tokens', config.get('fogbugz', 'active'), f.token)

@save_config
def logout(args):
    'Log off and clear the token for the active server'
    fb().logoff()
    config.remove_option('tokens', config.get('fogbugz', 'active'))

def newcase(args):
    pass

def remove(args):
    pass

def show(args):
    def areas(args):
        areas = fb().listAreas()
        for area in areas.findAll('area'):
            print '%s: %s' % (area.ixarea.contents[0], area.sarea.contents[0])
    
    def filters(args):
        filters = fb().listFilters()
        for filter in filters.findAll('filter'):
            print '%s: %s' % (filter['sfilter'], filter.contents[0])
    
    def projects(args):
        projects = fb().listProjects()
        for project in projects.findAll('project'):
            print '%s: %s' % (project.ixproject.contents[0], project.sproject.contents[0])
    
    def servers(args):
        for key, val in config.items('urls'):
            print '%s = %s' % (key, val)
    
    lists = {
              'areas': (areas, 'List areas in the current FogBugz instance'),
              'filters': (filters, 'List filters in the current FogBugz instance'),
              'projects': (projects, 'List projects in the current FogBugz instance'),
              'servers': (servers, 'List servers in the current FogBugz instance'),
            }

    dispatch('list', lists, args[1:])
    
@save_config
def switch(args):
    'Switch to the requested FogBugz server'
    alias = args[0]
    if not config.has_option('urls', alias):
        print 'not a known FogBugz server alias'
    else:
        config.set('fogbugz', 'active', alias)
    
def usage(main, commands):
    width = max(map(len, commands.keys()))
    print "FogBugz Command Line Client"
    print
    print '%s commands:' % (main,)
    print
    for key in commands.keys():
        print ' %s  %s' % (key.ljust(width), commands[key][1])
    print

def dispatch(main, commands, args, default = None):
    if len(args) == 0:
        if default:
            default()
        else:
            usage(main, commands)
    elif commands.has_key(args[0]):
        commands[args[0]][0](args[1:])
    else:
        usage(main, commands)
    
commands = {
             'active': (active, 'Display which FogBugz instance is active'),
             'add': (add, 'Add a new FogBugz instance to your config'),
             'list': (show, 'List various things in FogBugz'),
             'login': (login, 'Log in to the current FogBugz instance'),
             'logout': (logout, 'Log out of the current FogBugz instance'),
             'nc': (newcase, 'Add a new case to FogBugz'), # Move this to an alias list
             'newcase': (newcase, 'Add a new case to FogBugz'),
             'remove': (remove, 'Remove a FogBugz instance'),
             'switch': (switch, 'Switch the active FogBugz instance'),
           }

if __name__ == "__main__":
    dispatch('basic', commands, sys.argv[1:])

